import './globals.css'
import { Inter } from 'next/font/google'
import GlobalContext from './context'
import MainLayout from './components/layout/MainLayout'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Conduit',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <GlobalContext>
                    <MainLayout>
                        {children}
                    </MainLayout>
                </GlobalContext>
            </body>
        </html>
    )
}
